version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - dependencies
  - package-ecosystem: npm
    directory: '/microsite/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    labels:
      - dependencies
